// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPuBenUdCfs5cSVsUiTdoDLV5a2uv6rbo',
    appId: '1:911164758009:web:8453c176b2f893941b8f28',
    messagingSenderId: '911164758009',
    projectId: 'yefremov-firebase-notes-app',
    authDomain: 'yefremov-firebase-notes-app.firebaseapp.com',
    storageBucket: 'yefremov-firebase-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK73cezkuYob7Xzt63q4zwyDIZdaJPDus',
    appId: '1:911164758009:android:91f005b8abbca2c91b8f28',
    messagingSenderId: '911164758009',
    projectId: 'yefremov-firebase-notes-app',
    storageBucket: 'yefremov-firebase-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHAcaZmETC-ZoztJHj_nl40lBAeCXmvC4',
    appId: '1:911164758009:ios:d228ece30cfc11621b8f28',
    messagingSenderId: '911164758009',
    projectId: 'yefremov-firebase-notes-app',
    storageBucket: 'yefremov-firebase-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.yefremovFirebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHAcaZmETC-ZoztJHj_nl40lBAeCXmvC4',
    appId: '1:911164758009:ios:d228ece30cfc11621b8f28',
    messagingSenderId: '911164758009',
    projectId: 'yefremov-firebase-notes-app',
    storageBucket: 'yefremov-firebase-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.yefremovFirebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPuBenUdCfs5cSVsUiTdoDLV5a2uv6rbo',
    appId: '1:911164758009:web:8373135ab954a5821b8f28',
    messagingSenderId: '911164758009',
    projectId: 'yefremov-firebase-notes-app',
    authDomain: 'yefremov-firebase-notes-app.firebaseapp.com',
    storageBucket: 'yefremov-firebase-notes-app.firebasestorage.app',
  );
}
